// Package plate holds the types generated from the contract (contract/openapi.yaml).
//
// The generated file plate.gen.go is a BUILD PRODUCT, checked in so the test
// suite compiles in CI without a generation step, and regenerated by
// `go generate ./...`. Its symbols — the closed enums (Intent, ReasonCode,
// DeviceClass, MediaKind) and the schemas (Asset, VaultObject, Delivery, …) —
// are the exact types the service will implement, so the tests target the
// contract, not a hand-copied shadow of it. A shape change in the contract
// becomes a compile error here, which is the whole point of a generated
// contract (spec §6).
//
// The service itself is NOT in this package yet: this round is the test suite
// only. The tests drive thin interfaces (test/harness) against the real
// engines (imgproxy, ffmpeg) and assert on the real artifact.
package plate

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.8.0 -generate types -package plate -o plate.gen.go ../../contract/openapi.yaml
