// Package plate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package plate

import (
	"time"
)

// Defines values for DeliveryMode.
const (
	Granted DeliveryMode = "granted"
	Public  DeliveryMode = "public"
	Signed  DeliveryMode = "signed"
)

// Valid indicates whether the value is a known member of the DeliveryMode enum.
func (e DeliveryMode) Valid() bool {
	switch e {
	case Granted:
		return true
	case Public:
		return true
	case Signed:
		return true
	default:
		return false
	}
}

// Defines values for DeviceClass.
const (
	Desktop DeviceClass = "desktop"
	Mobile  DeviceClass = "mobile"
)

// Valid indicates whether the value is a known member of the DeviceClass enum.
func (e DeviceClass) Valid() bool {
	switch e {
	case Desktop:
		return true
	case Mobile:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Down     HealthStatus = "down"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Down:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Intent.
const (
	Detail    Intent = "detail"
	Grid      Intent = "grid"
	Lightbox  Intent = "lightbox"
	Loop      Intent = "loop"
	Original  Intent = "original"
	Poster    Intent = "poster"
	Thumbnail Intent = "thumbnail"
	Zoom1     Intent = "zoom_1"
	Zoom2     Intent = "zoom_2"
	Zoom3     Intent = "zoom_3"
)

// Valid indicates whether the value is a known member of the Intent enum.
func (e Intent) Valid() bool {
	switch e {
	case Detail:
		return true
	case Grid:
		return true
	case Lightbox:
		return true
	case Loop:
		return true
	case Original:
		return true
	case Poster:
		return true
	case Thumbnail:
		return true
	case Zoom1:
		return true
	case Zoom2:
		return true
	case Zoom3:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusFailed    JobStatus = "failed"
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusFailed:
		return true
	case JobStatusQueued:
		return true
	case JobStatusRunning:
		return true
	case JobStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for MediaKind.
const (
	Audio    MediaKind = "audio"
	Document MediaKind = "document"
	Image    MediaKind = "image"
	Video    MediaKind = "video"
)

// Valid indicates whether the value is a known member of the MediaKind enum.
func (e MediaKind) Valid() bool {
	switch e {
	case Audio:
		return true
	case Document:
		return true
	case Image:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// Defines values for ReasonCode.
const (
	ReasonCodeAuthoredBitrateExceeded    ReasonCode = "authored_bitrate_exceeded"
	ReasonCodeAuthoredCodecUnsupported   ReasonCode = "authored_codec_unsupported"
	ReasonCodeAuthoredLoopTooLong        ReasonCode = "authored_loop_too_long"
	ReasonCodeAuthoredResolutionExceeded ReasonCode = "authored_resolution_exceeded"
	ReasonCodeAuthoredTooLarge           ReasonCode = "authored_too_large"
	ReasonCodeDeleted                    ReasonCode = "deleted"
	ReasonCodeExceededDurationCeiling    ReasonCode = "exceeded_duration_ceiling"
	ReasonCodeExceededSizeCeiling        ReasonCode = "exceeded_size_ceiling"
	ReasonCodeFailed                     ReasonCode = "failed"
	ReasonCodeNotDerived                 ReasonCode = "not_derived"
	ReasonCodePending                    ReasonCode = "pending"
	ReasonCodeUnauthorized               ReasonCode = "unauthorized"
	ReasonCodeUnsupportedFormat          ReasonCode = "unsupported_format"
)

// Valid indicates whether the value is a known member of the ReasonCode enum.
func (e ReasonCode) Valid() bool {
	switch e {
	case ReasonCodeAuthoredBitrateExceeded:
		return true
	case ReasonCodeAuthoredCodecUnsupported:
		return true
	case ReasonCodeAuthoredLoopTooLong:
		return true
	case ReasonCodeAuthoredResolutionExceeded:
		return true
	case ReasonCodeAuthoredTooLarge:
		return true
	case ReasonCodeDeleted:
		return true
	case ReasonCodeExceededDurationCeiling:
		return true
	case ReasonCodeExceededSizeCeiling:
		return true
	case ReasonCodeFailed:
		return true
	case ReasonCodeNotDerived:
		return true
	case ReasonCodePending:
		return true
	case ReasonCodeUnauthorized:
		return true
	case ReasonCodeUnsupportedFormat:
		return true
	default:
		return false
	}
}

// Defines values for RenditionStatus.
const (
	RenditionStatusFailed     RenditionStatus = "failed"
	RenditionStatusNotDerived RenditionStatus = "not_derived"
	RenditionStatusPending    RenditionStatus = "pending"
	RenditionStatusReady      RenditionStatus = "ready"
)

// Valid indicates whether the value is a known member of the RenditionStatus enum.
func (e RenditionStatus) Valid() bool {
	switch e {
	case RenditionStatusFailed:
		return true
	case RenditionStatusNotDerived:
		return true
	case RenditionStatusPending:
		return true
	case RenditionStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for UploadTicketMethod.
const (
	PUT UploadTicketMethod = "PUT"
)

// Valid indicates whether the value is a known member of the UploadTicketMethod enum.
func (e UploadTicketMethod) Valid() bool {
	switch e {
	case PUT:
		return true
	default:
		return false
	}
}

// AccessLogEntry defines model for AccessLogEntry.
type AccessLogEntry struct {
	// Asset Service-generated. ULID or content hash.
	//
	// Examples: 01J9Z0K3Q4XR7NB8YF2WV6TCEH
	Asset *AssetId  `json:"asset,omitempty"`
	At    time.Time `json:"at"`

	// Intent The purpose a URL is for. Closed enum — a caller cannot invent one, and a
	// new media type cannot silently opt into a metered path (spec §4.1).
	Intent *Intent `json:"intent,omitempty"`
}

// AccountId Opaque foreign reference (spec Q2). Plate stores an id plus storage
// config — NO users, roles, or permissions. Identity is a separate concern.
type AccountId = string

// Asset One uploaded file: exactly one immutable vault object, plus zero or more
// renditions. Account-scoped. Note the vault object has NO delivery URL
// field — structurally, not by omission (spec §3.1).
type Asset struct {
	// Account Opaque foreign reference (spec Q2). Plate stores an id plus storage
	// config — NO users, roles, or permissions. Identity is a separate concern.
	Account AccountId `json:"account"`
	Created time.Time `json:"created"`

	// DeletedAt Set when deletion has been requested; bytes reconciled asynchronously.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`

	// Filename Human-readable original filename. Metadata, not identity.
	Filename *string `json:"filename,omitempty"`

	// Id Service-generated. ULID or content hash.
	//
	// Examples: 01J9Z0K3Q4XR7NB8YF2WV6TCEH
	Id AssetId `json:"id"`

	// Kind The broad class of the stored file. Drives which intents are valid and the delivery route.
	Kind       MediaKind   `json:"kind"`
	Renditions []Rendition `json:"renditions"`

	// Vault The immutable original. Probed metadata only — deliberately NO url field.
	// The single most important schema in this contract: the absence is the
	// design. Asking for a delivery URL here is a type error (spec §3.1).
	Vault VaultObject `json:"vault"`
}

// AssetId Service-generated. ULID or content hash.
//
// Examples: 01J9Z0K3Q4XR7NB8YF2WV6TCEH
type AssetId = string

// AssetPage defines model for AssetPage.
type AssetPage struct {
	Items []Asset `json:"items"`

	// NextCursor Opaque cursor for the next page, or null when exhausted.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// AuthoredRenditionBinding Binds an upload to an existing asset's rendition intent (Tier 2 V4.1 authored renditions).
type AuthoredRenditionBinding struct {
	// AssetId The existing asset this file is a rendition FOR. Must belong to the caller's account.
	//
	// Examples: 01J9Z0K3Q4XR7NB8YF2WV6TCEH
	AssetId AssetId `json:"asset_id"`

	// Intent The rendition intent this file provides (detail, loop, or poster for a video; detail for audio).
	Intent Intent `json:"intent"`
}

// Delivery A resolved, browser-reachable delivery URL and the bounds it was clamped to.
type Delivery struct {
	// Expires RFC 3339 expiry for signed/granted/original URLs; null for stable public URLs.
	Expires *time.Time `json:"expires,omitempty"`

	// Height Output height in pixels (image/video renditions).
	Height *int32 `json:"height,omitempty"`

	// Mode How a delivery URL is protected, chosen per asset (spec Q3.B). `public`
	// and `signed` keep Plate out of the byte path; `granted` puts a per-request
	// DB lookup in the hot path and is the only mode where revocation is the
	// product. `granted` carries TWO revocation guarantees by media kind:
	// granted images (imgproxy-signed) revoke within their (short, capped)
	// expiry; granted A/V (Plate `/download` + per-fetch liveness) revoke within
	// one grant-cache window. Both are effective within seconds, never instant.
	//
	// `public`: no grant, no expiry, stable and cacheable. An image `public` URL
	// carries an imgproxy signature because imgproxy verifies all URLs once
	// keyed; the signature is tamper-protection on the transform parameters, not
	// access control.
	Mode DeliveryMode `json:"mode"`

	// Url The browser-reachable URL. For `original` this is a short-lived
	// authenticated download URL — never a CDN URL, never embeddable.
	Url string `json:"url"`

	// Width Output width in pixels (image/video renditions).
	Width *int32 `json:"width,omitempty"`
}

// DeliveryMode How a delivery URL is protected, chosen per asset (spec Q3.B). `public`
// and `signed` keep Plate out of the byte path; `granted` puts a per-request
// DB lookup in the hot path and is the only mode where revocation is the
// product. `granted` carries TWO revocation guarantees by media kind:
// granted images (imgproxy-signed) revoke within their (short, capped)
// expiry; granted A/V (Plate `/download` + per-fetch liveness) revoke within
// one grant-cache window. Both are effective within seconds, never instant.
//
// `public`: no grant, no expiry, stable and cacheable. An image `public` URL
// carries an imgproxy signature because imgproxy verifies all URLs once
// keyed; the signature is tamper-protection on the transform parameters, not
// access control.
type DeliveryMode string

// DeliveryResolution The result of resolving an intent. Exactly one of `delivery` or `reason`
// is meaningful: a non-null `delivery` is a URL; a null `delivery` carries a
// `reason` and optional `detail`.
type DeliveryResolution struct {
	// Delivery The delivery URL and its bounds, or null when refused.
	Delivery *Delivery `json:"delivery"`

	// Detail Machine-readable context for a refusal. Fields are optional because they
	// depend on the reason (a duration ceiling carries seconds; an unsupported
	// format carries the container).
	Detail *RefusalDetail `json:"detail,omitempty"`

	// Intent The purpose a URL is for. Closed enum — a caller cannot invent one, and a
	// new media type cannot silently opt into a metered path (spec §4.1).
	Intent Intent `json:"intent"`

	// Reason Why no delivery rendition exists. Closed enum (spec §4.3). `unauthorized`
	// covers a missing/invalid/expired grant on a `granted` asset.
	//
	// `pending` and `not_derived` are the two a caller MUST be able to tell
	// apart: `pending` means the rendition is coming, so polling is correct;
	// `not_derived` means it will never exist because the upload asked for no
	// derivations (`skip_derivations`), so polling would wait forever. That
	// distinction is the whole reason `not_derived` is a member here and not
	// folded into `pending` or `failed` — see RenditionStatus.
	//
	// `deleted` means the asset is marked deleted and is no longer served.
	// The two-step delete is about the BYTES — the sweep reclaims them later —
	// not about continuing to serve in the meantime, so delivery refuses from
	// the moment `deleted_at` is set. It is its own member rather than
	// `unauthorized` (nothing about a deleted asset is an authorization
	// question) or a 404 (the owner can still read the asset and see
	// `deleted_at`, so the two endpoints would contradict each other).
	Reason *ReasonCode `json:"reason,omitempty"`
}

// DeviceClass Supplies the decoded-memory clamp input. Defaults to `mobile` (safe budget).
type DeviceClass string

// Error A structured error. `code` is a stable string a caller can branch on.
type Error struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Message Human-readable explanation. Never leaks another account's data.
	Message string `json:"message"`
}

// Export A long-lived, revocable owner capability over a frozen set of assets,
// yielding download URLs for their ORIGINAL bytes. The record is the
// capability: every download fetch re-checks it live, so revocation is
// immediate at the byte edge.
type Export struct {
	// Account Opaque foreign reference (spec Q2). Plate stores an id plus storage
	// config — NO users, roles, or permissions. Identity is a separate concern.
	Account AccountId `json:"account"`
	Assets  []AssetId `json:"assets"`
	Created time.Time `json:"created"`

	// Downloads Per-asset signed download URLs for the ORIGINAL bytes. Present only
	// while the export is live (not revoked, not expired) and download
	// signing is configured — re-derived on every read, never stored, so a
	// dead export cannot hand them out.
	Downloads *[]ExportDownload `json:"downloads,omitempty"`
	Expires   time.Time         `json:"expires"`
	Id        ExportId          `json:"id"`

	// Note Optional opaque label, or null.
	Note *string `json:"note,omitempty"`

	// RevokedAt When the export was revoked, or null if active.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
}

// ExportDownload defines model for ExportDownload.
type ExportDownload struct {
	// Asset Service-generated. ULID or content hash.
	//
	// Examples: 01J9Z0K3Q4XR7NB8YF2WV6TCEH
	Asset AssetId `json:"asset"`

	// Expires Same as the export's expiry — the URL's signature dies with the export.
	Expires time.Time `json:"expires"`

	// Url A signed Plate download URL for the asset's original bytes. Liveness-checked on every fetch.
	Url string `json:"url"`
}

// ExportId defines model for ExportId.
type ExportId = string

// ExportRequest Create an export over a frozen SET of assets.
type ExportRequest struct {
	// Assets The SET this export covers, frozen at issue time.
	Assets []AssetId `json:"assets"`

	// Expires When the export's download URLs stop working. Must be in the future
	// and at most 30 days out (the hard cap) — long-lived, never unbounded.
	Expires time.Time `json:"expires"`

	// Note Optional opaque label recording what this export is for. Plate does not interpret it.
	Note *string `json:"note,omitempty"`
}

// FinalizeRequest Signal a successful PUT so Plate can checksum, probe, and register the vault object.
type FinalizeRequest struct {
	// Checksum Client-computed checksum to verify against the stored object (e.g. sha256:...).
	Checksum string `json:"checksum"`
}

// Grant A first-class access record — "this link can see these files, until this
// date." Plate holds it; the caller owns why it exists (spec Q3).
type Grant struct {
	// AccessLog Observability — "opened 14 times, last Tuesday" (spec Q3).
	AccessLog *[]AccessLogEntry `json:"access_log,omitempty"`

	// Account Opaque foreign reference (spec Q2). Plate stores an id plus storage
	// config — NO users, roles, or permissions. Identity is a separate concern.
	Account AccountId `json:"account"`
	Assets  []AssetId `json:"assets"`
	Created time.Time `json:"created"`
	Expires time.Time `json:"expires"`
	Id      GrantId   `json:"id"`

	// Recipient Optional opaque recipient label, or null.
	Recipient *string `json:"recipient,omitempty"`

	// RevokedAt When the grant was revoked, or null if active.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
}

// GrantId defines model for GrantId.
type GrantId = string

// GrantRequest Create a grant over a frozen SET of assets (spec Q3).
type GrantRequest struct {
	// Assets The SET this grant covers, frozen at issue time. One grant per set, never per file.
	Assets []AssetId `json:"assets"`

	// Expires When access ends. Short by default (minutes) so revocation is effective within one window.
	Expires time.Time `json:"expires"`

	// Recipient Optional opaque recipient label. Plate does not model who this is.
	Recipient *string `json:"recipient,omitempty"`
}

// Header defines model for Header.
type Header struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// Health `ok` — every check passed. `degraded` — the API itself can serve, but a
// background dependency is unhealthy (the worker is not heartbeating, or the
// job queue is lagging); served with HTTP 200 so the API stays routable.
// `down` — a dependency the API needs to serve at all (database, storage)
// is unreachable; served with HTTP 503. A monitor should alert on BOTH a
// non-200 and a status other than `ok`.
type Health struct {
	// Checks Per-dependency results on /readyz, so a failing probe names what failed.
	Checks  *HealthChecks `json:"checks,omitempty"`
	Status  HealthStatus  `json:"status"`
	Version *string       `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	// Detail Short human-readable reason or measurement (e.g. `last heartbeat 4m12s ago`). Never carries account data.
	Detail *string `json:"detail,omitempty"`
	Ok     bool    `json:"ok"`
}

// HealthChecks Per-dependency results on /readyz, so a failing probe names what failed.
type HealthChecks struct {
	Db      *HealthCheck `json:"db,omitempty"`
	Queue   *HealthCheck `json:"queue,omitempty"`
	Storage *HealthCheck `json:"storage,omitempty"`
	Worker  *HealthCheck `json:"worker,omitempty"`
}

// Intent The purpose a URL is for. Closed enum — a caller cannot invent one, and a
// new media type cannot silently opt into a metered path (spec §4.1).
type Intent string

// Job Durable state for a queued derivation (A/V transcode). Survives worker restart (spec §5.2).
type Job struct {
	// Asset Service-generated. ULID or content hash.
	//
	// Examples: 01J9Z0K3Q4XR7NB8YF2WV6TCEH
	Asset   AssetId    `json:"asset"`
	Created *time.Time `json:"created,omitempty"`
	Id      JobId      `json:"id"`

	// Intent The purpose a URL is for. Closed enum — a caller cannot invent one, and a
	// new media type cannot silently opt into a metered path (spec §4.1).
	Intent Intent `json:"intent"`

	// Progress Fractional progress 0..1 while running.
	Progress *float64 `json:"progress,omitempty"`

	// Reason Why no delivery rendition exists. Closed enum (spec §4.3). `unauthorized`
	// covers a missing/invalid/expired grant on a `granted` asset.
	//
	// `pending` and `not_derived` are the two a caller MUST be able to tell
	// apart: `pending` means the rendition is coming, so polling is correct;
	// `not_derived` means it will never exist because the upload asked for no
	// derivations (`skip_derivations`), so polling would wait forever. That
	// distinction is the whole reason `not_derived` is a member here and not
	// folded into `pending` or `failed` — see RenditionStatus.
	//
	// `deleted` means the asset is marked deleted and is no longer served.
	// The two-step delete is about the BYTES — the sweep reclaims them later —
	// not about continuing to serve in the meantime, so delivery refuses from
	// the moment `deleted_at` is set. It is its own member rather than
	// `unauthorized` (nothing about a deleted asset is an authorization
	// question) or a 404 (the owner can still read the asset and see
	// `deleted_at`, so the two endpoints would contradict each other).
	Reason  *ReasonCode `json:"reason,omitempty"`
	Retries int32       `json:"retries"`
	Status  JobStatus   `json:"status"`
	Updated *time.Time  `json:"updated,omitempty"`
}

// JobId defines model for JobId.
type JobId = string

// JobStatus defines model for JobStatus.
type JobStatus string

// MediaKind The broad class of the stored file. Drives which intents are valid and the delivery route.
type MediaKind string

// ReasonCode Why no delivery rendition exists. Closed enum (spec §4.3). `unauthorized`
// covers a missing/invalid/expired grant on a `granted` asset.
//
// `pending` and `not_derived` are the two a caller MUST be able to tell
// apart: `pending` means the rendition is coming, so polling is correct;
// `not_derived` means it will never exist because the upload asked for no
// derivations (`skip_derivations`), so polling would wait forever. That
// distinction is the whole reason `not_derived` is a member here and not
// folded into `pending` or `failed` — see RenditionStatus.
//
// `deleted` means the asset is marked deleted and is no longer served.
// The two-step delete is about the BYTES — the sweep reclaims them later —
// not about continuing to serve in the meantime, so delivery refuses from
// the moment `deleted_at` is set. It is its own member rather than
// `unauthorized` (nothing about a deleted asset is an authorization
// question) or a 404 (the owner can still read the asset and see
// `deleted_at`, so the two endpoints would contradict each other).
type ReasonCode string

// RefusalDetail Machine-readable context for a refusal. Fields are optional because they
// depend on the reason (a duration ceiling carries seconds; an unsupported
// format carries the container).
type RefusalDetail struct {
	CeilingBytes *int64   `json:"ceiling_bytes,omitempty"`
	CeilingS     *float64 `json:"ceiling_s,omitempty"`
	Codec        *string  `json:"codec,omitempty"`
	Container    *string  `json:"container,omitempty"`
	DurationS    *float64 `json:"duration_s,omitempty"`
	SizeBytes    *int64   `json:"size_bytes,omitempty"`
}

// Rendition A bounded, browser-reachable derivative for one intent. The only tier a browser can reach.
type Rendition struct {
	DurationS *float64 `json:"duration_s,omitempty"`

	// HasAudio True only for `detail`; `loop` is always silent (spec §5.4).
	HasAudio *bool  `json:"has_audio,omitempty"`
	Height   *int32 `json:"height,omitempty"`

	// Intent The purpose a URL is for. Closed enum — a caller cannot invent one, and a
	// new media type cannot silently opt into a metered path (spec §4.1).
	Intent Intent `json:"intent"`

	// Reason Why no delivery rendition exists. Closed enum (spec §4.3). `unauthorized`
	// covers a missing/invalid/expired grant on a `granted` asset.
	//
	// `pending` and `not_derived` are the two a caller MUST be able to tell
	// apart: `pending` means the rendition is coming, so polling is correct;
	// `not_derived` means it will never exist because the upload asked for no
	// derivations (`skip_derivations`), so polling would wait forever. That
	// distinction is the whole reason `not_derived` is a member here and not
	// folded into `pending` or `failed` — see RenditionStatus.
	//
	// `deleted` means the asset is marked deleted and is no longer served.
	// The two-step delete is about the BYTES — the sweep reclaims them later —
	// not about continuing to serve in the meantime, so delivery refuses from
	// the moment `deleted_at` is set. It is its own member rather than
	// `unauthorized` (nothing about a deleted asset is an authorization
	// question) or a 404 (the owner can still read the asset and see
	// `deleted_at`, so the two endpoints would contradict each other).
	Reason *ReasonCode `json:"reason,omitempty"`

	// Status What this rendition row IS. Closed enum.
	//
	// - `ready`        derived and browser-reachable.
	// - `pending`      not derived yet; the worker will produce it.
	// - `failed`       we TRIED and it did not work, or a ceiling was breached
	//                  (the honest refusal) — `reason` carries which.
	// - `not_derived`  nobody asked. The upload set `skip_derivations`, so
	//                  this intent was never enqueued and nothing will derive
	//                  it automatically. `reason` stays NULL: the status
	//                  already says everything, and inventing a reason to
	//                  pair with it would carry no information.
	//                  Terminal for the AUTOMATIC path only — an explicit
	//                  rendition request overrides it (the owner changing
	//                  their mind is a new decision, and the renditions
	//                  endpoint treats this row as if no row existed).
	//
	// `failed` and `not_derived` are deliberately distinct: collapsing them
	// would make any "what is broken" count include archive-only assets
	// forever. At delivery the distinction surfaces as ReasonCode
	// `not_derived`, so a caller can tell "never coming" from `pending`.
	//
	// EXTENSION RULE: a new terminal state is a new enum member here plus an
	// explicit case in the delivery resolver — NEVER a sentinel in `reason`.
	// The resolver's status switch has a `default` arm, so an unhandled member
	// silently resolves as `pending` (a lie to a poller) rather than failing to
	// compile. Adding a member without its case is the bug this rule prevents.
	Status RenditionStatus `json:"status"`
	Width  *int32          `json:"width,omitempty"`
}

// RenditionRefusal The intent can never be satisfied for this asset.
type RenditionRefusal struct {
	// Detail Machine-readable context for a refusal. Fields are optional because they
	// depend on the reason (a duration ceiling carries seconds; an unsupported
	// format carries the container).
	Detail *RefusalDetail `json:"detail,omitempty"`

	// Intent The purpose a URL is for. Closed enum — a caller cannot invent one, and a
	// new media type cannot silently opt into a metered path (spec §4.1).
	Intent Intent `json:"intent"`

	// Reason Why no delivery rendition exists. Closed enum (spec §4.3). `unauthorized`
	// covers a missing/invalid/expired grant on a `granted` asset.
	//
	// `pending` and `not_derived` are the two a caller MUST be able to tell
	// apart: `pending` means the rendition is coming, so polling is correct;
	// `not_derived` means it will never exist because the upload asked for no
	// derivations (`skip_derivations`), so polling would wait forever. That
	// distinction is the whole reason `not_derived` is a member here and not
	// folded into `pending` or `failed` — see RenditionStatus.
	//
	// `deleted` means the asset is marked deleted and is no longer served.
	// The two-step delete is about the BYTES — the sweep reclaims them later —
	// not about continuing to serve in the meantime, so delivery refuses from
	// the moment `deleted_at` is set. It is its own member rather than
	// `unauthorized` (nothing about a deleted asset is an authorization
	// question) or a 404 (the owner can still read the asset and see
	// `deleted_at`, so the two endpoints would contradict each other).
	Reason ReasonCode `json:"reason"`
}

// RenditionRequest defines model for RenditionRequest.
type RenditionRequest struct {
	// Device Supplies the decoded-memory clamp input. Defaults to `mobile` (safe budget).
	Device *DeviceClass `json:"device,omitempty"`

	// Intent The purpose a URL is for. Closed enum — a caller cannot invent one, and a
	// new media type cannot silently opt into a metered path (spec §4.1).
	Intent Intent `json:"intent"`
}

// RenditionStatus What this rendition row IS. Closed enum.
//
//   - `ready`        derived and browser-reachable.
//   - `pending`      not derived yet; the worker will produce it.
//   - `failed`       we TRIED and it did not work, or a ceiling was breached
//     (the honest refusal) — `reason` carries which.
//   - `not_derived`  nobody asked. The upload set `skip_derivations`, so
//     this intent was never enqueued and nothing will derive
//     it automatically. `reason` stays NULL: the status
//     already says everything, and inventing a reason to
//     pair with it would carry no information.
//     Terminal for the AUTOMATIC path only — an explicit
//     rendition request overrides it (the owner changing
//     their mind is a new decision, and the renditions
//     endpoint treats this row as if no row existed).
//
// `failed` and `not_derived` are deliberately distinct: collapsing them
// would make any "what is broken" count include archive-only assets
// forever. At delivery the distinction surfaces as ReasonCode
// `not_derived`, so a caller can tell "never coming" from `pending`.
//
// EXTENSION RULE: a new terminal state is a new enum member here plus an
// explicit case in the delivery resolver — NEVER a sentinel in `reason`.
// The resolver's status switch has a `default` arm, so an unhandled member
// silently resolves as `pending` (a lie to a poller) rather than failing to
// compile. Adding a member without its case is the bug this rule prevents.
type RenditionStatus string

// UploadId defines model for UploadId.
type UploadId = string

// UploadRequest Ask for a presigned PUT. The caller declares content-type and size so the
// PUT can be bound to them; the caller does NOT choose the key — Plate owns
// key generation (spec §3.3).
type UploadRequest struct {
	// ContentType MIME type of the object to be uploaded. Bound into the presigned PUT.
	ContentType string `json:"content_type"`

	// Filename Optional human-readable name, recorded as metadata.
	Filename *string `json:"filename,omitempty"`

	// Rendition Authored rendition (Tier 2 V4.1). When present, this upload is the
	// FILE for a named rendition intent on an EXISTING asset — a studio's
	// own poster/loop/detail — not a new asset's original. Omit it (the
	// default) and the upload is an ordinary original, exactly as before.
	//
	// The file is stream-copy REMUXED (faststart, no re-encode) and, on
	// passing the authored ceilings for the intent (codec/resolution/
	// bitrate, plus loop's 30s cap and a size backstop), stored as a
	// `ready` rendition. Zero transcode. A ceiling breach fails with a
	// naming reason (authored_codec_unsupported / authored_resolution_
	// exceeded / authored_bitrate_exceeded / authored_loop_too_long /
	// authored_too_large). An intent that already has a `ready` rendition
	// is rejected 409 — replace is an explicit delete-then-author.
	Rendition *AuthoredRenditionBinding `json:"rendition,omitempty"`

	// SizeBytes Exact declared byte size. Bound into the presigned PUT's signature as the exact content-length — the object must be exactly this many bytes (a presigned PUT signs an exact length, not a range).
	SizeBytes int64 `json:"size_bytes"`

	// SkipDerivations Vault the original WITHOUT deriving anything from it. Additive and
	// optional: omit it (the default) and finalize behaves exactly as
	// before, auto-enqueuing `detail` for audio/video.
	//
	// Set it when the bytes are the point and no derivative is wanted — a
	// document of record, archive-only video. finalize then enqueues no
	// job and records EVERY derivable intent for the asset's kind as
	// RenditionStatus `not_derived`, so each one answers honestly: a
	// delivery call gets `delivery: null` + reason `not_derived` rather
	// than `pending`. Marking only the auto-enqueued intent would leave the
	// others absent, and absent still reads as `pending` — the same lie in
	// a different place. Without this flag the auto-enqueued `detail` is
	// unavoidable: there is no other opt-out.
	//
	// TERMINAL FOR THE AUTOMATIC PATH, REQUESTABLE ON DEMAND. Nothing will
	// ever derive these on its own — that is what `not_derived` promises.
	// But the flag declines the automatic enqueue at ingest; it is not a
	// ban on ever deriving. An archive-only video the studio later decides
	// to show is an ordinary change of mind, and the owner asking for a
	// rendition is a NEW decision that is honoured: a POST to the
	// renditions endpoint treats a `not_derived` row exactly as it treats
	// no row at all — it enqueues, and the job's result replaces the row.
	// The override lives at the point the request is made, not in a
	// re-finalize path.
	SkipDerivations *bool `json:"skip_derivations,omitempty"`
}

// UploadTicket A presigned PUT the browser can use for exactly one object, plus the id to finalize with.
type UploadTicket struct {
	// Expires PUT expiry — generous for a studio's slow connection (spec Q3.C).
	Expires time.Time `json:"expires"`

	// Headers Headers the browser must send verbatim with the PUT (e.g. Content-Type).
	Headers  []Header           `json:"headers"`
	Method   UploadTicketMethod `json:"method"`
	UploadId UploadId           `json:"upload_id"`

	// Url The presigned PUT URL. Writes exactly one object; bounded on key, type, and size.
	Url string `json:"url"`
}

// UploadTicketMethod defines model for UploadTicket.Method.
type UploadTicketMethod string

// VaultObject The immutable original. Probed metadata only — deliberately NO url field.
// The single most important schema in this contract: the absence is the
// design. Asking for a delivery URL here is a type error (spec §3.1).
type VaultObject struct {
	// Checksum Content checksum recorded at ingest (e.g. sha256:...).
	Checksum  string  `json:"checksum"`
	Codec     *string `json:"codec,omitempty"`
	Container *string `json:"container,omitempty"`

	// DurationS Probed duration in seconds (audio/video).
	DurationS *float64 `json:"duration_s,omitempty"`

	// Height Probed pixel height (image/video).
	Height *int32 `json:"height,omitempty"`

	// Key Storage key, `{account}/{asset-id}`. Server-to-server use only; never handed to a browser.
	Key       string `json:"key"`
	SizeBytes int64  `json:"size_bytes"`

	// Width Probed pixel width (image/video).
	Width *int32 `json:"width,omitempty"`
}

// AssetIdPath Service-generated. ULID or content hash.
//
// Examples: 01J9Z0K3Q4XR7NB8YF2WV6TCEH
type AssetIdPath = AssetId

// CursorQuery defines model for CursorQuery.
type CursorQuery = string

// ExportIdPath defines model for ExportIdPath.
type ExportIdPath = ExportId

// GrantIdPath defines model for GrantIdPath.
type GrantIdPath = GrantId

// LimitQuery defines model for LimitQuery.
type LimitQuery = int32

// BadRequest A structured error. `code` is a stable string a caller can branch on.
type BadRequest = Error

// Forbidden A structured error. `code` is a stable string a caller can branch on.
type Forbidden = Error

// NotFound A structured error. `code` is a stable string a caller can branch on.
type NotFound = Error

// Unauthorized A structured error. `code` is a stable string a caller can branch on.
type Unauthorized = Error

// ListAssetsParams defines parameters for ListAssets.
type ListAssetsParams struct {
	// Cursor Opaque pagination cursor from a previous page's `next_cursor`.
	Cursor *CursorQuery `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *LimitQuery  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ResolveDeliveryUrlParams defines parameters for ResolveDeliveryUrl.
type ResolveDeliveryUrlParams struct {
	// Intent The purpose the URL is for. Closed enum.
	Intent Intent `form:"intent" json:"intent"`

	// Device Device class, supplying the input to the decoded-memory clamp for
	// image intents. **Defaults to `mobile`** when unspecified — fail toward
	// the safe budget. A small viewport ALONE is sufficient to take the
	// mobile budget; never gate on `navigator.deviceMemory` (absent on
	// Safari, the browser that actually dies) (spec §4.2).
	Device *DeviceClass `form:"device,omitempty" json:"device,omitempty"`

	// Grant Opaque grant id, required only when the asset's delivery mode is
	// `granted`. Presenting it triggers a per-request DB lookup; absence or
	// invalidity on a granted asset yields `delivery: null`,
	// `reason: unauthorized` rather than a 200 URL (spec Q3.B).
	Grant *GrantId `form:"grant,omitempty" json:"grant,omitempty"`
}

// RequestRenditionJSONRequestBody defines body for RequestRendition for application/json ContentType.
type RequestRenditionJSONRequestBody = RenditionRequest

// CreateExportJSONRequestBody defines body for CreateExport for application/json ContentType.
type CreateExportJSONRequestBody = ExportRequest

// CreateGrantJSONRequestBody defines body for CreateGrant for application/json ContentType.
type CreateGrantJSONRequestBody = GrantRequest

// CreateUploadJSONRequestBody defines body for CreateUpload for application/json ContentType.
type CreateUploadJSONRequestBody = UploadRequest

// FinalizeUploadJSONRequestBody defines body for FinalizeUpload for application/json ContentType.
type FinalizeUploadJSONRequestBody = FinalizeRequest
